first_project/first_app/urls.py
from django.urls import path
from first_app import views

app_name = 'first_app'
urlpatterns = [
    path('index', views.index, name='index'),
    path('contact', views.contact, name='contact'),
    path('form', views.form_page, name='form_page'),
    path('relative', views.relative_page, name='relative_page'),
    path('other', views.other_page, name='other_page'),
    path('home', views.home, name='home'),
    path('registration', views.registration, name='registration'),
    path('login', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from first_app import views

urlpatterns = [
    path('first_app/', include("first_app.urls")),
    path('admin/', admin.site.urls),
]

first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.name

class WebPage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    webpage = models.ForeignKey(WebPage, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

first_project/first_app/forms.py
from django import forms
from django.contrib.auth.models import User
from first_app.models import UserProfileInfo

class FormName(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    text = forms.CharField(widget=forms.Textarea)

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from first_app.models import Topic, WebPage, AccessRecord
from first_app.forms import FormName, UserForm, UserProfileInfoForm

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
# Create your views here.

def index(request):
    webpages_list = AccessRecord.objects.order_by('date')
    date_dict = { 'access_records': webpages_list }

    return render(request, "first_app/index.html", context=date_dict)

def contact(request):
    return HttpResponse("<em>Contact!</em>")

def form_page(request):
    form = FormName()
    if request.method == "POST":
        form = FormName(request.POST)
        if form.is_valid():
            print("VALIDATION SUCCESS")
            print("Name: " + form.cleaned_data['name'])
            print("Email: " + form.cleaned_data['email'])
            print("Text: " + form.cleaned_data['text'])
    return render(request, 'first_app/form_page.html', { 'form': form })

def relative_page(request):
    return render(request, 'first_app/relative.html')

def other_page(request):
    return render(request, 'first_app/other.html')

def home(request):
    return render(request, 'first_app/home.html')

def registration(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'first_app/registration.html', {
    'user_form': user_form,
    'profile_form': profile_form,
    'registered': registered })

def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('first_app:index'))
            else:
                return HttpResponse('Account not active')
        else:
            return HttpResponse('Failed login')
    else:
        return render(request, 'first_app/login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('first_app:home'))

first_project/templates/first_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>BASE</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" />
  </head>
  <body>
    <nav class='navbar navbar-default navbar-static-top'>
      <div class='container'>
        <ul class='nav navbar-nav'>
          <li><a class='navbar-brand' href="{% url 'first_app:home' %}">HOME</a></li>
          <li><a class='navbar-link' href="{% url 'admin:index' %}">ADMIN</a></li>
          <li><a class='navbar-link' href="{% url 'first_app:registration' %}">REGISTRATION</a></li>

          {% if user.is_authenticated %}
            <li><a class='navbar-link' href="{% url 'first_app:logout' %}">LOGOUT</a></li>
          {% else %}
            <li><a class='navbar-link' href="{% url 'first_app:login' %}">LOGIN</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class='container'>
      {% block body_block %}
      {% endblock %}
    </div>

  </body>
</html>

first_project/templates/first_app/form_page.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Forms</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" />
  </head>
  <body>
    <div class="container">
      <h1>Fill out the form</h1>
      <form method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit"/>
      </form>

    </div>
  </body>
</html>

first_project/templates/first_app/home.html
{% extends "first_app/base.html" %}
{% block body_block %}
  <div class='jumbotron'>
    <h1>DJANGO LEVEL 5</h1>
  </div>
{% endblock %}

first_project/templates/first_app/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>First App</title>
  </head>
  <body>
    <h1>HELLO THIS IS AN IMAGE OF DAKEL</h1>
    <img src="{% static "images/dakel.jpg" %}" alt="Didn't show" />
    <h2>Here are your access records</h2>
    <div class="djangotwo">
      {%if access_records %}
      <table>
        <thead>
          <th>Site name</th>
          <th>Date accessed</th>
        </thead>
        {% for acc in access_records %}
        <tr>
          <td>{{ acc.name }}</td>
          <td>{{ acc.date }}</td>
        </tr>
        {% endfor %}
      </table>
      {% else %}
      <p>
        NO ACCESS RECORDS
      </p>
      {% endif %}
    </div>
  </body>
</html>

first_project/templates/first_app/login.html
{% extends "first_app/base.html" %}
{% block body_block %}
  <div class='jumbotron'>
    <h1>Please Log in</h1>
    <form method="POST" action="{% url 'first_app:login' %}" enctype='multipart/form-data'>
      {% csrf_token %}

      <label for="username">Username:</label>
      <input type='text' name="username" placeholder="Enter username"/>

      <label for="password">Password:</label>
      <input type='password' name="password"/>

      <input type='submit' name="" value="Login"/>
    </form>
  </div>
{% endblock %}

first_project/templates/first_app/other.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Other</title>
  </head>
  <body>
      <h1>This is OTHER</h1>
  </body>
</html>

first_project/templates/first_app/registration.html
{% extends "first_app/base.html" %}
{% load static %}
{% block body_block %}
  <div class='jumbotron'>
    {% if registered %}
      <h1>Thank you for registering</h1>
    {% else %}
      <h1>Register here</h1>
      <h3>Fill out the form:</h3>
      <form method="POST" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type='submit' value="Register"/>
      </form>
    {% endif %}
  </div>
{% endblock %}

first_project/templates/first_app/relative.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Relative</title>
  </head>
  <body>
    <h1>WELCOME TO RELATIVE PAGE</h1>
    <a href="{% url 'first_app:other_page' %}">OTHER PAGE</a>
  </body>
</html>